{
 "title": "NightFlow Service Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"$application\"} |= ``"
    }
   ]
  }
 ]
}