server:
  port: 8090 # Auth Service portu

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nightflow_auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Geliştirme aşamasında tabloları otomatik oluştursun
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"

jwt:
  secret: ${JWT_SECRET:404E835266556A586K3272357538782T413F4438482B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:604800000} # 7 gün (milisaniye)
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
