spring:
  application:
    name: shopping-cart-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}

logging:
  level:
    com.nightflow.shoppingcartservice.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
